apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.1
  listenersServiceTemplate:
    spec:
      type: NodePort
      ports:
        - name: tcp
          port: 1883
          targetPort: 1883
          nodePort: 1883
        - name: ws
          port: 8083
          targetPort: 8083
          nodePort: 8083
        - name: wss
          port: 8084
          targetPort: 8084
          nodePort: 8084
        - name: mqtt-tls
          port: 8883
          targetPort: 8883
          nodePort: 8883

  dashboardServiceTemplate:
    spec:
      type: NodePort
