services:
  mqtt-broker:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    volumes:
      - mqtt-data:/opt/emqx/data
    networks:
      - five-zero-network

  s7-adapter:
    build:
      context: ./five-zero-adapter
      dockerfile: Dockerfile
    container_name: s7-adapter
    depends_on:
      - mqtt-broker
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/config/s7-adapter.json
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./config/s7-adapter.json:/app/config/s7-adapter.json
    restart: unless-stopped
    networks:
      - five-zero-network

  shelly-adapter:
    build:
      context: ./five-zero-adapter
      dockerfile: Dockerfile
    container_name: shelly-adapter
    depends_on:
      - mqtt-broker
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/config/shelly-adapter.json
      - PORT=3002
    ports:
      - "3002:3002"
    volumes:
      - ./config/shelly-adapter.json:/app/config/shelly-adapter.json
    restart: unless-stopped
    networks:
      - five-zero-network

  anomaly-detector:
    image: 5.0-robotics/workspace-monitor
    build:
      context: ./five-zero-anomaly-detection
      dockerfile: Dockerfile
    container_name: anomaly-detector
    depends_on:
      - mqtt-broker
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 4G
    env_file: './five-zero-anomaly-detection/.env'
    ports:
      - "3004:3004"
    volumes:
      - ./config/anomaly-detector.json:/app/config/anomaly-detector.json
    restart: unless-stopped
    networks:
      - five-zero-network
   

  dashboard:
    build:
      context: ./five-zero-dashboard
      dockerfile: Dockerfile
    container_name: five-zero-dashboard
    depends_on:
      - mqtt-broker
    environment:
      - NODE_ENV=production
      - MQTT_BROKER_URL=ws://localhost:8083/mqtt
      - MQTT_CLIENT_ID=dashboard-client
      - MQTT_USERNAME=dev
      - MQTT_PASSWORD=dev

      # For Cloud LiveKit setup
      # - LIVEKIT_URL=wss://cnc-demo-7wj97mwz.livekit.cloud
      # - LIVEKIT_BACKEND_URL=wss://cnc-demo-7wj97mwz.livekit.cloud
      # - LIVEKIT_API_KEY=APIeNJYiSJnTXTD
      # - LIVEKIT_API_SECRET=3kTnOeRPRfXyenmRcjlGXg57obwcEL9mSljHyzEn1RYA
     
      # For Local LiveKit Setup
      - LIVEKIT_URL=ws://10.10.10.10:7880
      - LIVEKIT_BACKEND_URL=ws://10.10.10.10:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
  
    ports:
      - "3000:3000"
    # volumes:
    #   - ./config/dashboard.json:/app/config/dashboard.json
    restart: unless-stopped
    networks:
      - five-zero-network

  # uccnc-adapter:
  #   build:
  #     context: ./five-zero-adapter
  #     dockerfile: Dockerfile
  #   container_name: uccnc-adapter
  #   depends_on:
  #     - mqtt-broker
  #   environment:
  #     - NODE_ENV=production
  #     - CONFIG_PATH=/app/config/uccnc-adapter.json
  #     - PORT=3003
  #   ports:
  #     - "3003:3003"
  #   volumes:
  #     - ./config/uccnc-adapter.json:/app/config/uccnc-adapter.json
  #   restart: unless-stopped
  #   networks:
  #     - five-zero-network

networks:
  five-zero-network:
    driver: bridge

volumes:
  mqtt-data:
