/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cnc.glb --types 
*/
"use client";

import * as THREE from 'three'
import React, { JSX, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { PivotControls } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


type GLTFResult = GLTF & {
  nodes: {
    Body1077: THREE.Mesh
    Body1108: THREE.Mesh
    Body1105: THREE.Mesh
    Body1064: THREE.Mesh
    Body1063: THREE.Mesh
    Body1062: THREE.Mesh
    Body1061: THREE.Mesh
    Body1060: THREE.Mesh
    Body1059: THREE.Mesh
    Body1058: THREE.Mesh
    Body1057: THREE.Mesh
    Body1056: THREE.Mesh
    Body1055: THREE.Mesh
    Body1107: THREE.Mesh
    Body1054: THREE.Mesh
    Body1053: THREE.Mesh
    Body1052: THREE.Mesh
    Body1051: THREE.Mesh
    Body1050: THREE.Mesh
    Body1049: THREE.Mesh
    Body2002: THREE.Mesh
    Body3009: THREE.Mesh
    Body1160: THREE.Mesh
    Body1160_1: THREE.Mesh
    Body1160_2: THREE.Mesh
    Body1160_3: THREE.Mesh
    Body1160_4: THREE.Mesh
    Body1160_5: THREE.Mesh
    Body1159: THREE.Mesh
    Body1159_1: THREE.Mesh
    Body1159_2: THREE.Mesh
    Body1159_3: THREE.Mesh
    Body1159_4: THREE.Mesh
    Body1159_5: THREE.Mesh
    Body1109: THREE.Mesh
    Body1158: THREE.Mesh
    Body1158_1: THREE.Mesh
    Body1158_2: THREE.Mesh
    Body1158_3: THREE.Mesh
    Body1158_4: THREE.Mesh
    Body1158_5: THREE.Mesh
    Body1157: THREE.Mesh
    Body1157_1: THREE.Mesh
    Body1157_2: THREE.Mesh
    Body1157_3: THREE.Mesh
    Body1157_4: THREE.Mesh
    Body1157_5: THREE.Mesh
    Body1044: THREE.Mesh
    Body1043: THREE.Mesh
    Body1042: THREE.Mesh
    Body1041: THREE.Mesh
    Body1040: THREE.Mesh
    Body1039: THREE.Mesh
    Body1038: THREE.Mesh
    Body2006: THREE.Mesh
    Body1090: THREE.Mesh
    Body3004: THREE.Mesh
    Body1037: THREE.Mesh
    Body2010: THREE.Mesh
    Body1036: THREE.Mesh
    Body1035: THREE.Mesh
    Body2: THREE.Mesh
    Body3010: THREE.Mesh
    Body4004: THREE.Mesh
    Body5001: THREE.Mesh
    Body6002: THREE.Mesh
    Body1081: THREE.Mesh
    Body7003: THREE.Mesh
    Body8002: THREE.Mesh
    Body9001: THREE.Mesh
    Body10003: THREE.Mesh
    Body11003: THREE.Mesh
    Body12002: THREE.Mesh
    Body13: THREE.Mesh
    Body14: THREE.Mesh
    Body15: THREE.Mesh
    Body16: THREE.Mesh
    Body1088: THREE.Mesh
    Body17002: THREE.Mesh
    Body18: THREE.Mesh
    Body19001: THREE.Mesh
    Body20001: THREE.Mesh
    Body21001: THREE.Mesh
    Body22: THREE.Mesh
    Body23002: THREE.Mesh
    Body24: THREE.Mesh
    Body25: THREE.Mesh
    Body26: THREE.Mesh
    Body1110: THREE.Mesh
    Body27: THREE.Mesh
    Body28: THREE.Mesh
    Body29001: THREE.Mesh
    Body30: THREE.Mesh
    Body31002: THREE.Mesh
    Body32002: THREE.Mesh
    Body33002: THREE.Mesh
    Body34002: THREE.Mesh
    Body35002: THREE.Mesh
    Body36002: THREE.Mesh
    Body1104: THREE.Mesh
    Body37002: THREE.Mesh
    Body38001: THREE.Mesh
    Body39001: THREE.Mesh
    Body1034: THREE.Mesh
    Body1033: THREE.Mesh
    Body2011: THREE.Mesh
    Body3005: THREE.Mesh
    Body1032: THREE.Mesh
    Body1031: THREE.Mesh
    Body1030: THREE.Mesh
    Body1102: THREE.Mesh
    Body1029: THREE.Mesh
    Body1028: THREE.Mesh
    Body1027: THREE.Mesh
    Body1026: THREE.Mesh
    Body1137: THREE.Mesh
    Body1137_1: THREE.Mesh
    Body1137_2: THREE.Mesh
    Body1137_3: THREE.Mesh
    Body1137_4: THREE.Mesh
    Body1137_5: THREE.Mesh
    Body1136: THREE.Mesh
    Body1136_1: THREE.Mesh
    Body1136_2: THREE.Mesh
    Body1136_3: THREE.Mesh
    Body1136_4: THREE.Mesh
    Body1136_5: THREE.Mesh
    Body1135: THREE.Mesh
    Body1135_1: THREE.Mesh
    Body1135_2: THREE.Mesh
    Body1135_3: THREE.Mesh
    Body1135_4: THREE.Mesh
    Body1135_5: THREE.Mesh
    Body1134: THREE.Mesh
    Body1134_1: THREE.Mesh
    Body1134_2: THREE.Mesh
    Body1134_3: THREE.Mesh
    Body1134_4: THREE.Mesh
    Body1134_5: THREE.Mesh
    Body1021: THREE.Mesh
    Body1020: THREE.Mesh
    Body1093: THREE.Mesh
    Body2012: THREE.Mesh
    Body3008: THREE.Mesh
    Body1019: THREE.Mesh
    Body1018: THREE.Mesh
    Body1017: THREE.Mesh
    Body1016: THREE.Mesh
    Body1015: THREE.Mesh
    Body1014: THREE.Mesh
    Body2005: THREE.Mesh
    Body3001: THREE.Mesh
    Body1080: THREE.Mesh
    Body1111: THREE.Mesh
    Body1013: THREE.Mesh
    Body2004: THREE.Mesh
    Body3003: THREE.Mesh
    Body4002: THREE.Mesh
    Body5002: THREE.Mesh
    Body6003: THREE.Mesh
    Body7: THREE.Mesh
    Body8: THREE.Mesh
    Body9: THREE.Mesh
    Body10: THREE.Mesh
    Body1103: THREE.Mesh
    Body11: THREE.Mesh
    Body12003: THREE.Mesh
    Body13003: THREE.Mesh
    Body14002: THREE.Mesh
    Body15002: THREE.Mesh
    Body16002: THREE.Mesh
    Body17: THREE.Mesh
    Body18002: THREE.Mesh
    Body19002: THREE.Mesh
    Body20002: THREE.Mesh
    Body1078: THREE.Mesh
    Body21002: THREE.Mesh
    Body22001: THREE.Mesh
    Body23: THREE.Mesh
    Body24001: THREE.Mesh
    Body25001: THREE.Mesh
    Body26001: THREE.Mesh
    Body27002: THREE.Mesh
    Body28002: THREE.Mesh
    Body29002: THREE.Mesh
    Body30001: THREE.Mesh
    Body1089: THREE.Mesh
    Body31001: THREE.Mesh
    Body32: THREE.Mesh
    Body33001: THREE.Mesh
    Body34: THREE.Mesh
    Body35: THREE.Mesh
    Body36: THREE.Mesh
    Body37: THREE.Mesh
    Body38: THREE.Mesh
    Body39: THREE.Mesh
    Body1124: THREE.Mesh
    Body1124_1: THREE.Mesh
    Body1124_2: THREE.Mesh
    Body1124_3: THREE.Mesh
    Body1124_4: THREE.Mesh
    Body1124_5: THREE.Mesh
    Body1085: THREE.Mesh
    Body1011: THREE.Mesh
    Body1122: THREE.Mesh
    Body1122_1: THREE.Mesh
    Body1122_2: THREE.Mesh
    Body1122_3: THREE.Mesh
    Body1122_4: THREE.Mesh
    Body1122_5: THREE.Mesh
    Body1121: THREE.Mesh
    Body1121_1: THREE.Mesh
    Body1121_2: THREE.Mesh
    Body1121_3: THREE.Mesh
    Body1121_4: THREE.Mesh
    Body1121_5: THREE.Mesh
    Body1120: THREE.Mesh
    Body1120_1: THREE.Mesh
    Body1120_2: THREE.Mesh
    Body1120_3: THREE.Mesh
    Body1120_4: THREE.Mesh
    Body1120_5: THREE.Mesh
    Body1007: THREE.Mesh
    Body1006: THREE.Mesh
    Body1005: THREE.Mesh
    Body1004: THREE.Mesh
    Body1003: THREE.Mesh
    Body1002: THREE.Mesh
    Body1101: THREE.Mesh
    Body2021: THREE.Mesh
    Body2021_1: THREE.Mesh
    Body2021_2: THREE.Mesh
    Body2021_3: THREE.Mesh
    Body2021_4: THREE.Mesh
    Body2021_5: THREE.Mesh
    Body2021_6: THREE.Mesh
    Body2021_7: THREE.Mesh
    Body2021_8: THREE.Mesh
    Body2021_9: THREE.Mesh
    Body2021_10: THREE.Mesh
    Body2021_11: THREE.Mesh
    Body2021_12: THREE.Mesh
    Body2021_13: THREE.Mesh
    Body1001: THREE.Mesh
    Body2009: THREE.Mesh
    Body3002: THREE.Mesh
    Body4003: THREE.Mesh
    Body1096: THREE.Mesh
    Body1097: THREE.Mesh
    Body1098: THREE.Mesh
    Body1082: THREE.Mesh
    Body1086: THREE.Mesh
    Body1083: THREE.Mesh
    Body1084: THREE.Mesh
    Body1087: THREE.Mesh
    Body1100: THREE.Mesh
    Body2007: THREE.Mesh
    Body3006: THREE.Mesh
    Body1106: THREE.Mesh
    Body2003: THREE.Mesh
    Body3: THREE.Mesh
    Body4001: THREE.Mesh
    Body1094: THREE.Mesh
    Body5: THREE.Mesh
    Body6001: THREE.Mesh
    Body7001: THREE.Mesh
    Body8001: THREE.Mesh
    Body9002: THREE.Mesh
    Body10001: THREE.Mesh
    Body11001: THREE.Mesh
    Body12001: THREE.Mesh
    Body13002: THREE.Mesh
    Body14001: THREE.Mesh
    Body1092: THREE.Mesh
    Body15001: THREE.Mesh
    Body16001: THREE.Mesh
    Body17001: THREE.Mesh
    Body18001: THREE.Mesh
    Body19: THREE.Mesh
    Body20: THREE.Mesh
    Body21: THREE.Mesh
    Body22002: THREE.Mesh
    Body23001: THREE.Mesh
    Body24002: THREE.Mesh
    Body1079: THREE.Mesh
    Body25002: THREE.Mesh
    Body26002: THREE.Mesh
    Body27001: THREE.Mesh
    Body28001: THREE.Mesh
    Body29: THREE.Mesh
    Body30002: THREE.Mesh
    Body31: THREE.Mesh
    Body32001: THREE.Mesh
    Body33: THREE.Mesh
    Body34001: THREE.Mesh
    Body1091: THREE.Mesh
    Body35001: THREE.Mesh
    Body36001: THREE.Mesh
    Body37001: THREE.Mesh
    Body38002: THREE.Mesh
    Body39002: THREE.Mesh
    Body1: THREE.Mesh
    Body2001: THREE.Mesh
    Body3007: THREE.Mesh
    Body4: THREE.Mesh
    Body5003: THREE.Mesh
    Body1095: THREE.Mesh
    Body6: THREE.Mesh
    Body7002: THREE.Mesh
    Body8003: THREE.Mesh
    Body9003: THREE.Mesh
    Body10002: THREE.Mesh
    Body11002: THREE.Mesh
    Body12: THREE.Mesh
    Body13001: THREE.Mesh
    Body1076: THREE.Mesh
    Body1075: THREE.Mesh
    Body1099: THREE.Mesh
    Body1074: THREE.Mesh
    Body1073: THREE.Mesh
    Body1072: THREE.Mesh
    Body1071: THREE.Mesh
    Body1070: THREE.Mesh
    Body1069: THREE.Mesh
    Body1068: THREE.Mesh
    Body1067: THREE.Mesh
    Body1066: THREE.Mesh
    Body1065: THREE.Mesh
  }
  materials: {
    F_c7248d41b94b4513af5fc28cd5e3d975: THREE.MeshPhysicalMaterial
    F_a43c225432f744308044b61861661265: THREE.MeshPhysicalMaterial
    F_f4e8b3ba1def404cbdc9956ab4a1c01d: THREE.MeshPhysicalMaterial
    F_fece7f3009f244e19bf2684bc530d45f: THREE.MeshPhysicalMaterial
    F_b0234ef9a9d44a20ae7e0d2c5da15302: THREE.MeshPhysicalMaterial
    F_6f33dabea2244db48b1eb089fa2b63fa: THREE.MeshPhysicalMaterial
    F_ebd976c3c5b340008ba811c3ce9789ab: THREE.MeshPhysicalMaterial
    F_d641c9ad5e0f40c097f10145e55987f0: THREE.MeshPhysicalMaterial
    F_5ea1b6233cde46aab8dd60b3969ebb81: THREE.MeshPhysicalMaterial
    F_4039f4112435420b980a61bea58aef5b: THREE.MeshPhysicalMaterial
    F_3ea268051510440e8995add3ccb9af08: THREE.MeshPhysicalMaterial
    F_6d322a9d5e9842bcb681779d1f3885b2: THREE.MeshPhysicalMaterial
    F_109d8168c1f24f648b7ca93c1e0f7cd5: THREE.MeshPhysicalMaterial
    F_3cfc9c4d9b7e45f38e975b977abf88ef: THREE.MeshPhysicalMaterial
    F_d9df2cdc076e47a396e983299917fb38: THREE.MeshPhysicalMaterial
    F_5879e0c34acf464f8534f9b86a80fc78: THREE.MeshPhysicalMaterial
    F_8526c5fff99440ab87e96071a6eb60f3: THREE.MeshPhysicalMaterial
    F_aa6919c0e1b64e2b8047a6ecf0ec93b5: THREE.MeshPhysicalMaterial
    F_fb91f9479e974ad68e7f31e41a4e30bc: THREE.MeshPhysicalMaterial
    F_1c9c86724cba40eaac458c9fb40e23e9: THREE.MeshPhysicalMaterial
    F_a4abd2a43adf4e7085e22efd27a767a5: THREE.MeshPhysicalMaterial
    F_49c186d582bc4eb88dbd6cdb53a83e49: THREE.MeshPhysicalMaterial
    F_ac8bdf7965f641a98e896a0a8a8603b4: THREE.MeshPhysicalMaterial
    F_70a25391c2654c6e81caf2e24a28ba3c: THREE.MeshPhysicalMaterial
    F_6b786166c4c447cbaec938cbdc87577a: THREE.MeshPhysicalMaterial
    F_b3911f1c098646c0b56a87acecf0e375: THREE.MeshPhysicalMaterial
    F_852fd9459f584ba2a787c10210ca1deb: THREE.MeshPhysicalMaterial
  }
  animations: any[]
}

export function Cnc({ x = 0, y = 0, ...props }: JSX.IntrinsicElements['group'] & { x?: number; y?: number }) {
  const { nodes, materials } = useGLTF('/models/cnc.glb') as unknown as GLTFResult


  const xAxisRef = useRef<THREE.Group>(null)
  const yAxisRef = useRef<THREE.Group>(null)

  // Apply the X and Y positions on each frame
  useFrame(() => {
    if (xAxisRef.current) {
      xAxisRef.current.position.x = x - 700
    }
    if (yAxisRef.current) {
      yAxisRef.current.position.y = -y - 1100 * -1
    }
  })


  return (

    <group {...props} dispose={null} >
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>

        <group> {/* Base */}
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body18001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body19.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body20.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body21.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body22002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body23001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body24002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[-358.107, -7584.485, -939.193]} rotation={[0, 1.178, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1079.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[-0.001, 0, 0]} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body25002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body26002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body27001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body28001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body29.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body30002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body31.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body32001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body33.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body34001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[120.33, 9515.132, -363.261]} rotation={[Math.PI, 0.393, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1091.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.002, 0, 0]} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body35001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body36001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body37001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body38002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body39002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body1.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body2001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body3007.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body4.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body5003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[8639.986, -61.341, -648.1]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1095.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body6.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body7002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body8003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body9003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body10002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body11002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body12.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 709, -741]}>
            <mesh geometry={nodes.Body13001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[-180, -790, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1075.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-301.868, 9099.484, -1042.32]} rotation={[0, 0.393, Math.PI / 2]}>
            <mesh geometry={nodes.Body1099.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.001, 0, 0]} scale={10} />
          </group>
          <group position={[-180, -265, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1074.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[140.5, -790, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1073.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[140.5, -265, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1072.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, 0, -768]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1071.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -364, -768]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1070.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -728, -768]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1069.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -1092, -768]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1068.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -790, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1067.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[119.5, -790, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1066.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[440, -790, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1065.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <mesh geometry={nodes.Body1077.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          <mesh geometry={nodes.Body1076.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />



          <group position={[-8639.986, -61.341, -658.1]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1108.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[311.106, 9099.484, -1038.49]} rotation={[0, -0.393, Math.PI / 2]}>
            <mesh geometry={nodes.Body1105.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.001, 0, 0]} scale={10} />
          </group>
          <group position={[320.5, -790, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1064.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -1154, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1063.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[440, -1154, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1062.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[119.5, -1154, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1061.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[320.5, -1154, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1060.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -1518, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1059.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[320.5, -1518, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1058.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[440, -1518, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1057.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[119.5, -1518, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1056.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[119.5, -1882, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1055.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, 740, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1107.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[320.5, -1882, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1054.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[440, -1882, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1053.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -1882, -765]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1052.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, 710, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1051.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-661, 710, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1050.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -786.47, -766]} rotation={[0, -1.188, 0]}>
            <mesh geometry={nodes.Body1049.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -786.47, -766]} rotation={[0, -1.188, 0]}>
            <mesh geometry={nodes.Body2002.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -786.47, -766]} rotation={[0, -1.188, 0]}>
            <mesh geometry={nodes.Body3009.geometry} material={materials.F_a43c225432f744308044b61861661265} scale={10} />
          </group>
          <group position={[195.847, 730, -717.032]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1109.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[655.2, 420.418, 3.488]}>
            <mesh geometry={nodes.Body1030.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[1316.2, 420.418, 3.488]}>
            <mesh geometry={nodes.Body1029.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-8639.986, 61.342, -648.1]} rotation={[Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1102.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-120.33, -9515.132, -363.261]} rotation={[Math.PI, -0.393, Math.PI / 2]}>
            <mesh geometry={nodes.Body1110.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.002, 0, 0]} scale={10} />
          </group>
          <group position={[131.847, 730, -717.032]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1090.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -800, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1081.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[354.277, -9114.485, -948.431]} rotation={[0, -1.178, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1088.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-301.868, 7569.486, -1042.32]} rotation={[0, 0.393, Math.PI / 2]}>
            <mesh geometry={nodes.Body1104.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.001, 0, 0]} scale={10} />
          </group>


          <group position={[8639.986, 61.342, -658.1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1093.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>


          <group position={[354.277, -7584.485, -948.431]} rotation={[0, -1.178, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1080.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[-0.001, 0, 0]} scale={10} />
          </group>
          <group position={[-358.107, -9114.485, -939.193]} rotation={[0, 1.178, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1111.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>

          <group position={[120.33, 7985.132, -363.261]} rotation={[Math.PI, 0.393, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1103.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.001, 0, 0]} scale={10} />
          </group>

          <group position={[5, 7985.132, -1093.245]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Body1098.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} position={[0.001, 0, 0]} scale={10} />
          </group>
          <group position={[0, -790, 0]}>
            <mesh geometry={nodes.Body1082.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-5, -7985.132, -1093.245]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1086.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -790, 0]}>
            <mesh geometry={nodes.Body1083.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -790, 0]}>
            <mesh geometry={nodes.Body1084.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -795, -766]}>
            <mesh geometry={nodes.Body1087.geometry} material={materials.F_6d322a9d5e9842bcb681779d1f3885b2} scale={10} />
          </group>
          <group position={[0, -847.35, -766]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1100.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -847.35, -766]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body2007.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -847.35, -766]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body3006.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1106.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body2003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body3.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body4001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[-120.33, -7985.132, -363.261]} rotation={[Math.PI, -0.393, Math.PI / 2]}>
            <mesh geometry={nodes.Body1094.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body5.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body6001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body7001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body8001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body9002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body10001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body11001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body12001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body13002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body14001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 740, -730.47]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.Body1092.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body15001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body16001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, -720, -766]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body17001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>


          <group position={[0, 790, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1096.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, 790, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1097.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>


          <group position={[-143.33, -748.165, -720.47]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1089.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -790, 0]}>
            <mesh geometry={nodes.Body1101.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -740, 0]}>
            <mesh geometry={nodes.Body1085.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>




        </group> {/* Base */}

        <group ref={yAxisRef}> {/* Y Axis */}

          <group position={[329.99, -424.317, -736.749]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group scale={10}>
              <mesh geometry={nodes.Body1160.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
              <mesh geometry={nodes.Body1160_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
              <mesh geometry={nodes.Body1160_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
              <mesh geometry={nodes.Body1160_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
              <mesh geometry={nodes.Body1160_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
              <mesh geometry={nodes.Body1160_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
            </group>
          </group>
          <group position={[329.99, -551.027, -736.749]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group scale={10}>
              <mesh geometry={nodes.Body1159.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
              <mesh geometry={nodes.Body1159_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
              <mesh geometry={nodes.Body1159_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
              <mesh geometry={nodes.Body1159_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
              <mesh geometry={nodes.Body1159_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
              <mesh geometry={nodes.Body1159_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
            </group>
          </group>

          <group position={[-330.99, -424.317, -736.749]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group scale={10}>
              <mesh geometry={nodes.Body1158.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
              <mesh geometry={nodes.Body1158_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
              <mesh geometry={nodes.Body1158_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
              <mesh geometry={nodes.Body1158_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
              <mesh geometry={nodes.Body1158_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
              <mesh geometry={nodes.Body1158_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
            </group>
          </group>
          <group position={[-330.99, -551.027, -736.749]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group scale={10}>
              <mesh geometry={nodes.Body1157.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
              <mesh geometry={nodes.Body1157_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
              <mesh geometry={nodes.Body1157_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
              <mesh geometry={nodes.Body1157_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
              <mesh geometry={nodes.Body1157_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
              <mesh geometry={nodes.Body1157_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
            </group>
          </group>
          <group position={[154.355, -543.886, 124.842]}>
            <mesh geometry={nodes.Body1044.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-155.37, -355.882, 124.842]} rotation={[0, 0, Math.PI]}>
            <mesh geometry={nodes.Body1043.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[380.928, -1089.379, -750.749]} rotation={[0, 0, -1.571]}>
            <mesh geometry={nodes.Body1042.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-381.942, -1089.383, -750.749]} rotation={[0, 0, -1.571]}>
            <mesh geometry={nodes.Body1041.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-461.992, -530.79, -1129.738]} rotation={[0, 0, -1.571]}>
            <mesh geometry={nodes.Body1040.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-461.982, -641.524, -997.446]} rotation={[0, 0, 1.571]}>
            <mesh geometry={nodes.Body1039.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-519.348, -465.795, -1129.738]} rotation={[3.013, -1.57, 1.442]}>
            <mesh geometry={nodes.Body1038.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-519.348, -465.795, -1129.738]} rotation={[3.013, -1.57, 1.442]}>
            <mesh geometry={nodes.Body2006.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>

          <group position={[-519.348, -465.795, -1129.738]} rotation={[3.013, -1.57, 1.442]}>
            <mesh geometry={nodes.Body3004.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[199.494, -1792.318, -218.389]}>
            <mesh geometry={nodes.Body1037.geometry} material={materials.F_d641c9ad5e0f40c097f10145e55987f0} scale={10} />
          </group>
          <group position={[199.494, -1792.318, -218.389]}>
            <mesh geometry={nodes.Body2010.geometry} material={materials.F_5ea1b6233cde46aab8dd60b3969ebb81} scale={10} />
          </group>
          <group position={[476.02, -893.128, -998.953]} rotation={[0, 0, 1.571]}>
            <mesh geometry={nodes.Body1036.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body1035.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body2.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body3010.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body4004.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body5001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body6002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body7003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body8002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body9001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body10003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body11003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body12002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body13.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body14.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body15.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body16.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>

          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body17002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body18.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body19001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body20001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body21001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body22.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body23002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body24.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body25.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body26.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body27.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body28.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body29001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body30.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body31002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body32002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body33002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body34002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body35002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body36002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body37002.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body38001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[476.981, -465.706, -1129.738]} rotation={[0, 0, -3.142]}>
            <mesh geometry={nodes.Body39001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
          </group>
          <group position={[0, 0, -1129.749]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Body1034.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-455.498, -465.79, -1129.738]} rotation={[-2.395, 0, -1.571]}>
            <mesh geometry={nodes.Body1033.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-455.498, -465.79, -1129.738]} rotation={[-2.395, 0, -1.571]}>
            <mesh geometry={nodes.Body2011.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-455.498, -465.79, -1129.738]} rotation={[-2.395, 0, -1.571]}>
            <mesh geometry={nodes.Body3005.geometry} material={materials.F_a43c225432f744308044b61861661265} scale={10} />
          </group>
          <group position={[-461.93, -1227.29, -859.738]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Body1032.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-461.93, -1227.29, -739.738]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Body1031.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[154.355, -543.886, -742.249]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Body1028.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[-14.51, -476.813, -742.249]} rotation={[0, 0, Math.PI]}>
            <mesh geometry={nodes.Body1027.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
          </group>
          <group position={[0, -315.886, -766.249]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Body1026.geometry} material={materials.F_3ea268051510440e8995add3ccb9af08} scale={10} />
          </group>







          < group ref={xAxisRef} >

            < group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]} >
              <mesh geometry={nodes.Body30001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>



            <group position={[457.078, -234.598, -1200.07]} rotation={[-0.112, 0.644, -3.094]}>
              <mesh geometry={nodes.Body4003.geometry} material={materials.F_852fd9459f584ba2a787c10210ca1deb} scale={10} />
            </group>



            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body31001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body32.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body33001.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body34.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body35.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body36.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body37.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body38.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body39.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[295.231, -422.825, -1374.792]} rotation={[Math.PI, 0, 3.142]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1124.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1124_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1124_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1124_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1124_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1124_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[-18.73, -397.865, -22.5]}>
              <mesh geometry={nodes.Body1011.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[403.231, -422.815, -1374.792]} rotation={[Math.PI, 0, 3.142]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1122.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1122_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1122_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1122_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1122_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1122_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[403.231, -422.815, -1218.492]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1121.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1121_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1121_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1121_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1121_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1121_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[295.231, -422.825, -1218.492]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1120.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1120_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1120_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1120_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1120_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1120_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[-275.771, -392.876, -1016.642]}>
              <mesh geometry={nodes.Body1007.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[273.207, -369.495, -1379.642]} rotation={[0.129, -1.57, 1.699]}>
              <mesh geometry={nodes.Body1006.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[349.229, -397.829, -1439.642]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Body1005.geometry} material={materials.F_3ea268051510440e8995add3ccb9af08} scale={10} />
            </group>
            <group position={[306.128, -474.727, -1633.054]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh geometry={nodes.Body1004.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[-275.773, -377.876, -1016.642]}>
              <mesh geometry={nodes.Body1003.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[349.218, -272.32, -1426.642]} rotation={[0, 1.571, 0]}>
              <mesh geometry={nodes.Body1002.geometry} material={materials.F_109d8168c1f24f648b7ca93c1e0f7cd5} scale={10} />
            </group>
            <group position={[349.218, -272.32, -1426.642]} rotation={[0, 1.571, 0]}>
              <group scale={10}>
                <mesh geometry={nodes.Body2021.geometry} material={materials.F_3cfc9c4d9b7e45f38e975b977abf88ef} />
                <mesh geometry={nodes.Body2021_1.geometry} material={materials.F_d9df2cdc076e47a396e983299917fb38} />
                <mesh geometry={nodes.Body2021_2.geometry} material={materials.F_5879e0c34acf464f8534f9b86a80fc78} />
                <mesh geometry={nodes.Body2021_3.geometry} material={materials.F_8526c5fff99440ab87e96071a6eb60f3} />
                <mesh geometry={nodes.Body2021_4.geometry} material={materials.F_aa6919c0e1b64e2b8047a6ecf0ec93b5} />
                <mesh geometry={nodes.Body2021_5.geometry} material={materials.F_fb91f9479e974ad68e7f31e41a4e30bc} />
                <mesh geometry={nodes.Body2021_6.geometry} material={materials.F_1c9c86724cba40eaac458c9fb40e23e9} />
                <mesh geometry={nodes.Body2021_7.geometry} material={materials.F_a4abd2a43adf4e7085e22efd27a767a5} />
                <mesh geometry={nodes.Body2021_8.geometry} material={materials.F_49c186d582bc4eb88dbd6cdb53a83e49} />
                <mesh geometry={nodes.Body2021_9.geometry} material={materials.F_ac8bdf7965f641a98e896a0a8a8603b4} />
                <mesh geometry={nodes.Body2021_10.geometry} material={materials.F_70a25391c2654c6e81caf2e24a28ba3c} />
                <mesh geometry={nodes.Body2021_11.geometry} material={materials.F_6b786166c4c447cbaec938cbdc87577a} />
                <mesh geometry={nodes.Body2021_12.geometry} material={materials.F_b3911f1c098646c0b56a87acecf0e375} />
                <mesh geometry={nodes.Body2021_13.geometry} material={materials.F_109d8168c1f24f648b7ca93c1e0f7cd5} />
              </group>
            </group>
            <group position={[457.078, -234.598, -1200.07]} rotation={[-0.112, 0.644, -3.094]}>
              <mesh geometry={nodes.Body1001.geometry} material={materials.F_852fd9459f584ba2a787c10210ca1deb} scale={10} />
            </group>
            <group position={[457.078, -234.598, -1200.07]} rotation={[-0.112, 0.644, -3.094]}>
              <mesh geometry={nodes.Body2009.geometry} material={materials.F_852fd9459f584ba2a787c10210ca1deb} scale={10} />
            </group>
            <group position={[457.078, -234.598, -1200.07]} rotation={[-0.112, 0.644, -3.094]}>
              <mesh geometry={nodes.Body3002.geometry} material={materials.F_852fd9459f584ba2a787c10210ca1deb} scale={10} />
            </group>



            <group position={[427.397, -490.462, -1189.728]} rotation={[0, 1.571, 0]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1137.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1137_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1137_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1137_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1137_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1137_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[427.397, -490.462, -1069.748]} rotation={[0, 1.571, 0]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1136.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1136_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1136_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1136_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1136_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1136_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[271.098, -490.476, -1069.748]} rotation={[0, -1.571, 0]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1135.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1135_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1135_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1135_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1135_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1135_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[271.098, -490.476, -1189.728]} rotation={[0, -1.571, 0]}>
              <group scale={10}>
                <mesh geometry={nodes.Body1134.geometry} material={materials.F_f4e8b3ba1def404cbdc9956ab4a1c01d} />
                <mesh geometry={nodes.Body1134_1.geometry} material={materials.F_fece7f3009f244e19bf2684bc530d45f} />
                <mesh geometry={nodes.Body1134_2.geometry} material={materials.F_b0234ef9a9d44a20ae7e0d2c5da15302} />
                <mesh geometry={nodes.Body1134_3.geometry} material={materials.F_6f33dabea2244db48b1eb089fa2b63fa} />
                <mesh geometry={nodes.Body1134_4.geometry} material={materials.F_a43c225432f744308044b61861661265} />
                <mesh geometry={nodes.Body1134_5.geometry} material={materials.F_ebd976c3c5b340008ba811c3ce9789ab} />
              </group>
            </group>
            <group position={[274.245, -460.476, -1046.207]}>
              <mesh geometry={nodes.Body1021.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[1075.241, -492.504, -1778.205]} rotation={[0, 0, -3.142]}>
              <mesh geometry={nodes.Body1020.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[1075.241, -492.504, -1778.205]} rotation={[0, 0, -3.142]}>
              <mesh geometry={nodes.Body2012.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[1075.241, -492.504, -1778.205]} rotation={[0, 0, -3.142]}>
              <mesh geometry={nodes.Body3008.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[-690.895, -1140.15, -1196.625]} rotation={[Math.PI / 2, 0, Math.PI]}>
              <mesh geometry={nodes.Body1019.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[-582.895, -1140.14, -1196.625]} rotation={[Math.PI / 2, 0, Math.PI]}>
              <mesh geometry={nodes.Body1018.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>

            <group position={[349.239, -397.839, -1525.206]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Body1017.geometry} material={materials.F_6d322a9d5e9842bcb681779d1f3885b2} scale={10} />
            </group>
            <group position={[408.243, -437.131, -1205.748]} rotation={[-Math.PI, 0, -1.571]}>
              <mesh geometry={nodes.Body1016.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[519.245, -465.454, -1129.728]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh geometry={nodes.Body1015.geometry} material={materials.F_3ea268051510440e8995add3ccb9af08} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1577.557]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.Body1014.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1577.557]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.Body2005.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1577.557]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.Body3001.geometry} material={materials.F_c7248d41b94b4513af5fc28cd5e3d975} scale={10} />
            </group>

            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body1013.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body2004.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>
            <group position={[349.239, -397.839, -1450.207]} rotation={[Math.PI, -1.571, 0]}>
              <mesh geometry={nodes.Body3003.geometry} material={materials.F_4039f4112435420b980a61bea58aef5b} scale={10} />
            </group>

          </group> {/* X Axis */}





        </group> {/* Y Axis */}


        {/* Split */}


      </group >
    </group >

  )
}


useGLTF.preload('/models/cnc.glb')
