/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kuka.glb --types --keepnames --keepgroups --shadows 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
    Body2: THREE.Mesh
    Body1004_1: THREE.Mesh
    Body1004_2: THREE.Mesh
    Body1006_1: THREE.Mesh
    Body1006_2: THREE.Mesh
    Body1008_1: THREE.Mesh
    Body1008_2: THREE.Mesh
    Body1003_1: THREE.Mesh
    Body1003_2: THREE.Mesh
    Body1009_1: THREE.Mesh
    Body1009_2: THREE.Mesh
    Body1007: THREE.Mesh
    Body1005: THREE.Mesh
    Body2001: THREE.Mesh
    Body3001: THREE.Mesh
    Body4: THREE.Mesh
    Body3: THREE.Mesh
    Body5001: THREE.Mesh
    Body6: THREE.Mesh
    Body1001: THREE.Mesh
    Body1002: THREE.Mesh
    Body4001_1: THREE.Mesh
    Body4001_2: THREE.Mesh
    Body5_1: THREE.Mesh
    Body5_2: THREE.Mesh
    Body6001_1: THREE.Mesh
    Body6001_2: THREE.Mesh
    Body7: THREE.Mesh
    Body8: THREE.Mesh
    Body9_1: THREE.Mesh
    Body9_2: THREE.Mesh
    Body10: THREE.Mesh
  }
  materials: {
    F_0ae20f6605d04fb8a3cc2bdaf8d51809: THREE.MeshPhysicalMaterial
    F_6f35eb9b73fe4f1cb76294f64ac5759e: THREE.MeshPhysicalMaterial
    F_d2d2c43f203941aaa911b152f25ce08b: THREE.MeshPhysicalMaterial
    F_e9c8e786462048cea8257356eb72378e: THREE.MeshPhysicalMaterial
    F_35f0a684add946c39145321af8f132ed: THREE.MeshPhysicalMaterial
    F_479eb3dee2b244c7bb9f326f3893d30c: THREE.MeshPhysicalMaterial
    F_18bdf38dd4f1435083cee56e297ff546: THREE.MeshPhysicalMaterial
    F_cb46189d18034e8681001b75bc7fda29: THREE.MeshPhysicalMaterial
    F_7b74e9160e164e958f11c2bc3fc0e98c: THREE.MeshPhysicalMaterial
  }
  animations: any
}

export function Kuka(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/models/kuka.glb') as GLTFResult
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]} position={[0.75, 0.58, 0]}>
      <group name="Scene">
        <group name="InsideParts_Kuka_arm_v1" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <group name="MeshInstance">
            <mesh name="Body1" castShadow receiveShadow geometry={nodes.Body1.geometry} material={materials.F_0ae20f6605d04fb8a3cc2bdaf8d51809} scale={10} />
          </group>
          <group name="MeshInstance_1">
            <mesh name="Body2" castShadow receiveShadow geometry={nodes.Body2.geometry} material={materials.F_6f35eb9b73fe4f1cb76294f64ac5759e} scale={10} />
          </group>
          <group name="MeshInstance_10" position={[-0.002, 0, -1.5]} rotation={[-Math.PI, 1.569, -Math.PI]}>
            <group name="Body1004" scale={10}>
              <mesh name="Body1004_1" castShadow receiveShadow geometry={nodes.Body1004_1.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} />
              <mesh name="Body1004_2" castShadow receiveShadow geometry={nodes.Body1004_2.geometry} material={materials.F_e9c8e786462048cea8257356eb72378e} />
            </group>
          </group>
          <group name="MeshInstance_11" position={[0.224, 37.675, 144.805]} rotation={[3.142, 1.569, 2.762]}>
            <group name="Body1006" scale={10}>
              <mesh name="Body1006_1" castShadow receiveShadow geometry={nodes.Body1006_1.geometry} material={materials.F_e9c8e786462048cea8257356eb72378e} />
              <mesh name="Body1006_2" castShadow receiveShadow geometry={nodes.Body1006_2.geometry} material={materials.F_35f0a684add946c39145321af8f132ed} />
            </group>
          </group>
          <group name="MeshInstance_12" position={[0.12, 11.826, 77.415]} rotation={[Math.PI, 1.569, 2.847]}>
            <group name="Body1008" scale={10}>
              <mesh name="Body1008_1" castShadow receiveShadow geometry={nodes.Body1008_1.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} />
              <mesh name="Body1008_2" castShadow receiveShadow geometry={nodes.Body1008_2.geometry} material={materials.F_e9c8e786462048cea8257356eb72378e} />
            </group>
          </group>
          <group name="MeshInstance_13" position={[-0.672, 1695.89, -433.986]} rotation={[0, -1.569, -2.847]}>
            <group name="Body1003" scale={10}>
              <mesh name="Body1003_1" castShadow receiveShadow geometry={nodes.Body1003_1.geometry} material={materials.F_e9c8e786462048cea8257356eb72378e} />
              <mesh name="Body1003_2" castShadow receiveShadow geometry={nodes.Body1003_2.geometry} material={materials.F_35f0a684add946c39145321af8f132ed} />
            </group>
          </group>
          <group name="MeshInstance_14" position={[-2.296, 1169.555, -1484.084]} rotation={[0, -1.569, -Math.PI / 2]}>
            <group name="Body1009" scale={10}>
              <mesh name="Body1009_1" castShadow receiveShadow geometry={nodes.Body1009_1.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} />
              <mesh name="Body1009_2" castShadow receiveShadow geometry={nodes.Body1009_2.geometry} material={materials.F_e9c8e786462048cea8257356eb72378e} />
            </group>
          </group>
          <group name="MeshInstance_15" position={[839.302, 1169.555, -342.548]} rotation={[-Math.PI, 0.302, Math.PI / 2]}>
            <mesh name="Body1007" castShadow receiveShadow geometry={nodes.Body1007.geometry} material={materials.F_6f35eb9b73fe4f1cb76294f64ac5759e} scale={10} />
          </group>
          <group name="MeshInstance_16" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body1005" castShadow receiveShadow geometry={nodes.Body1005.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_17" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body2001" castShadow receiveShadow geometry={nodes.Body2001.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_18" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body3001" castShadow receiveShadow geometry={nodes.Body3001.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_19" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body4" castShadow receiveShadow geometry={nodes.Body4.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_2">
            <mesh name="Body3" castShadow receiveShadow geometry={nodes.Body3.geometry} material={materials.F_6f35eb9b73fe4f1cb76294f64ac5759e} scale={10} />
          </group>
          <group name="MeshInstance_20" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body5001" castShadow receiveShadow geometry={nodes.Body5001.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_21" position={[-53.812, 576.744, -716.042]} rotation={[Math.PI / 2, 0, -0.146]}>
            <mesh name="Body6" castShadow receiveShadow geometry={nodes.Body6.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} scale={10} />
          </group>
          <group name="MeshInstance_22" position={[-88.796, 644.955, -718.528]} rotation={[0, -0.841, -Math.PI]}>
            <mesh name="Body1001" castShadow receiveShadow geometry={nodes.Body1001.geometry} material={materials.F_479eb3dee2b244c7bb9f326f3893d30c} scale={10} />
          </group>
          <group name="MeshInstance_23" position={[50.652, 644.955, -739.102]} rotation={[-Math.PI, -1.138, 0]}>
            <mesh name="Body1002" castShadow receiveShadow geometry={nodes.Body1002.geometry} material={materials.F_479eb3dee2b244c7bb9f326f3893d30c} scale={10} />
          </group>
          <group name="MeshInstance_3">
            <group name="Body4001" scale={10}>
              <mesh name="Body4001_1" castShadow receiveShadow geometry={nodes.Body4001_1.geometry} material={materials.F_18bdf38dd4f1435083cee56e297ff546} />
              <mesh name="Body4001_2" castShadow receiveShadow geometry={nodes.Body4001_2.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} />
            </group>
          </group>
          <group name="MeshInstance_4">
            <group name="Body5" scale={10}>
              <mesh name="Body5_1" castShadow receiveShadow geometry={nodes.Body5_1.geometry} material={materials.F_cb46189d18034e8681001b75bc7fda29} />
              <mesh name="Body5_2" castShadow receiveShadow geometry={nodes.Body5_2.geometry} material={materials.F_7b74e9160e164e958f11c2bc3fc0e98c} />
            </group>
          </group>
          <group name="MeshInstance_5">
            <group name="Body6001" scale={10}>
              <mesh name="Body6001_1" castShadow receiveShadow geometry={nodes.Body6001_1.geometry} material={materials.F_cb46189d18034e8681001b75bc7fda29} />
              <mesh name="Body6001_2" castShadow receiveShadow geometry={nodes.Body6001_2.geometry} material={materials.F_7b74e9160e164e958f11c2bc3fc0e98c} />
            </group>
          </group>
          <group name="MeshInstance_6">
            <mesh name="Body7" castShadow receiveShadow geometry={nodes.Body7.geometry} material={materials.F_6f35eb9b73fe4f1cb76294f64ac5759e} scale={10} />
          </group>
          <group name="MeshInstance_7">
            <mesh name="Body8" castShadow receiveShadow geometry={nodes.Body8.geometry} material={materials.F_0ae20f6605d04fb8a3cc2bdaf8d51809} scale={10} />
          </group>
          <group name="MeshInstance_8">
            <group name="Body9" scale={10}>
              <mesh name="Body9_1" castShadow receiveShadow geometry={nodes.Body9_1.geometry} material={materials.F_d2d2c43f203941aaa911b152f25ce08b} />
              <mesh name="Body9_2" castShadow receiveShadow geometry={nodes.Body9_2.geometry} material={materials.F_6f35eb9b73fe4f1cb76294f64ac5759e} />
            </group>
          </group>
          <group name="MeshInstance_9">
            <mesh name="Body10" castShadow receiveShadow geometry={nodes.Body10.geometry} material={materials.F_18bdf38dd4f1435083cee56e297ff546} scale={10} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kuka.glb')
